# nixpacks.toml
# Minimal configuration to tell nixpacks to use the `website` subdirectory
# as the project root. Different platforms/readers may use different keys
# (for example `project`, `source`, or `project_dir`). This file sets
# the common variants so most consumers can detect the intended directory.

# Primary project directory used by many tools
project = "website"

# Alternative common key name
project_dir = "website"

# Another variant sometimes used
source = "website"

# If your deployment platform expects a different shape, tell me the
# exact schema and I'll update this file accordingly.
