// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// This file is generated by `x-env generate`.

export interface EnvKey {
	MUTATE_TOKEN: string;
	NEXT_PUBLIC_DATASET: string;
	NEXT_PUBLIC_PROJECT_ID: string;
}

export interface PublicEnvKey {
	NEXT_PUBLIC_DATASET: string;
	NEXT_PUBLIC_PROJECT_ID: string;
}

export interface PrivateEnvKey {
	MUTATE_TOKEN: string;
}

export type EnvKeyName = keyof EnvKey;
export type PublicEnvKeyName = keyof PublicEnvKey;
export type PrivateEnvKeyName = keyof PrivateEnvKey;
